if(KEYFERRY_BOARD STREQUAL "")
    message(FATAL_ERROR "Select a board with -DKEYFERRY_BOARD=<profile>")
endif()

set(KEYFERRY_BOARD_DIR "${CMAKE_CURRENT_LIST_DIR}/${KEYFERRY_BOARD}")
set(KEYFERRY_BOARD_MANIFEST "${KEYFERRY_BOARD_DIR}/board.json")
set(KEYFERRY_BOARD_SDKCONFIG_DEFAULTS "${KEYFERRY_BOARD_DIR}/sdkconfig.defaults")
if(NOT EXISTS "${KEYFERRY_BOARD_MANIFEST}" OR
   NOT EXISTS "${KEYFERRY_BOARD_SDKCONFIG_DEFAULTS}")
    message(FATAL_ERROR "Unknown or incomplete keyferry board profile: ${KEYFERRY_BOARD}")
endif()

find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(KEYFERRY_BOARD_GENERATOR "${CMAKE_CURRENT_LIST_DIR}/../../../scripts/gen_board_profile.py")
set(KEYFERRY_BOARD_INCLUDE_DIR "${CMAKE_BINARY_DIR}/generated-board")
set(KEYFERRY_BOARD_HEADER "${KEYFERRY_BOARD_INCLUDE_DIR}/board_profile.h")
file(MAKE_DIRECTORY "${KEYFERRY_BOARD_INCLUDE_DIR}")
execute_process(
    COMMAND "${Python3_EXECUTABLE}" "${KEYFERRY_BOARD_GENERATOR}"
            --input "${KEYFERRY_BOARD_MANIFEST}"
            --output "${KEYFERRY_BOARD_HEADER}"
    RESULT_VARIABLE KEYFERRY_BOARD_RESULT
    OUTPUT_VARIABLE KEYFERRY_BOARD_OUTPUT
    ERROR_VARIABLE KEYFERRY_BOARD_ERROR
)
if(NOT KEYFERRY_BOARD_RESULT EQUAL 0)
    string(STRIP "${KEYFERRY_BOARD_ERROR}" KEYFERRY_BOARD_ERROR)
    message(FATAL_ERROR "Invalid keyferry board profile: ${KEYFERRY_BOARD_ERROR}")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${KEYFERRY_BOARD_MANIFEST}" "${KEYFERRY_BOARD_GENERATOR}")
