// @generated by scripts/gen_protocol.py from protocol/messages.yaml.
// Do not edit by hand.

pub mod discovery {
    pub const MAGIC: [u8; 4] = *b"KFHB";
    pub const VERSION: u8 = 1;
    pub const BEACON_SIZE: usize = 22;
    pub const PORT: u16 = 43917;
}

pub mod ble_transport {
    pub const VERSION: u8 = 1;
    pub const SERVICE_UUID: [u8; 16] = [
        0xA2, 0xE3, 0xF2, 0xA8, 0xA4, 0xFF, 0x4E, 0xD8, 0x9B, 0x68, 0xDD, 0xE0, 0xE3, 0xAD, 0x76,
        0x91,
    ];
    pub const GATEWAY_TO_DEVICE_UUID: [u8; 16] = [
        0x74, 0xBE, 0xFF, 0x36, 0x34, 0x49, 0x44, 0xDF, 0x8D, 0xAF, 0x0D, 0xA9, 0xC1, 0x36, 0xF4,
        0xAB,
    ];
    pub const DEVICE_TO_GATEWAY_UUID: [u8; 16] = [
        0xC9, 0x12, 0xCB, 0xBF, 0xA2, 0xF9, 0x41, 0x8F, 0x98, 0x5C, 0xCC, 0x62, 0x79, 0x38, 0x9C,
        0x54,
    ];
    pub const MINIMUM_ATT_MTU: usize = 23;
    pub const PREFERRED_ATT_MTU: usize = 247;
    pub const MAXIMUM_FRAGMENT_BYTES: usize = 244;
    pub const RECEIVE_RING_BYTES: usize = 1024;
    pub const TRANSMIT_STAGING_BYTES: usize = 244;
    pub const CONNECTION_METADATA_MAX_BYTES: usize = 256;
    pub const CCCD_SETUP_TIMEOUT_MS: usize = 20000;
    pub const AUTHENTICATION_TIMEOUT_MS: usize = 20000;
    pub const PROGRESS_TIMEOUT_MS: usize = 5000;
    pub const OPERATION_TIMEOUT_MS: usize = 8000;
    pub const HOST_CANDIDATE_TIMEOUT_MS: usize = 40000;
    pub const ADVERTISING_DELAY_MS: usize = 5000;
    pub const WIFI_PREFERENCE_MS: usize = 15000;
    pub const WIFI_RETRY_INTERVAL_MS: usize = 30000;
    pub const FAILED_CANDIDATES_BEFORE_WIFI_RETRY: usize = 3;
}

pub mod configuration {
    pub const MAX_WIFI_PROFILES: usize = 8;
    pub const MAX_PAIRED_HOSTS: usize = 8;
    pub const MAX_SSID_BYTES: usize = 32;
    pub const MAX_WIFI_CREDENTIAL_BYTES: usize = 63;
    pub const MAX_SERVER_NAME_BYTES: usize = 253;
    pub const MAX_CA_CERTIFICATE_BYTES: usize = 1024;
    pub const FIXED_HEADER_BYTES: usize = 52;
    pub const WIFI_RECORD_BYTES: usize = 103;
    pub const HOST_RECORD_BYTES: usize = 1369;
    pub const PAYLOAD_BYTES: usize = 11828;
}

pub mod file_handoff {
    pub const MAX_FILE_BYTES: usize = 262144;
    pub const MAX_CHUNK_BYTES: usize = 200;
    pub const STATUS_BYTES: usize = 10;
    pub const MAX_FILES: usize = 16;
    pub const MAX_NAME_BYTES: usize = 64;
    pub const FILE_SET_STATUS_BYTES: usize = 11;
    pub const MAX_BUNDLE_BYTES: usize = 1 + MAX_FILES * (1 + MAX_NAME_BYTES + 4) + MAX_FILE_BYTES;
}

pub mod roaming {
    pub const VERSION: u8 = 2;
    pub const DEVICE_TLS_PORT: u16 = 7443;
    pub const INSTALLATION_ID_BYTES: usize = 16;
    pub const OWNER_ID_BYTES: usize = 16;
    pub const DEVICE_ID_BYTES: usize = 16;
    pub const RECOVERY_SECRET_BYTES: usize = 32;
    pub const DEVICE_LINK_SECRET_BYTES: usize = 32;
    pub const P256_SPKI_BYTES: usize = 91;
    pub const ROUTE_PROOF_SECRET_BYTES: usize = 32;
    pub const ROUTE_PROOF_TAG_BYTES: usize = 32;
    pub const ROUTE_PROOF_BODY_BYTES: usize = 201;
    pub const ROUTE_PROOF_FIELDS_BYTES: usize = 178;
    pub const ROUTE_PROOF_RESPONSE_BYTES: usize = 210;
    pub const POLICY_AUTH_TAG_BYTES: usize = 32;
    pub const REVOCATION_ENTRY_BYTES: usize = 16;
    pub const ROAMING_CONFIG_FIXED_HEADER_BYTES: usize = 192;
    pub const ROAMING_CONFIG_PAYLOAD_BYTES: usize = 3064;
    pub const POLICY_HASH_INPUT_BYTES: usize = 3018;
    pub const POLICY_AUTH_INPUT_BYTES: usize = 55;
    pub const MAXIMUM_REVOKED_INSTALLATIONS: usize = 64;
    pub const ROUTE_PROOF_TTL_MS: usize = 5000;
    pub const GATEWAY_HANDOFF_START_PAYLOAD_BYTES: usize = 96;
    pub const GATEWAY_HANDOFF_ACCEPT_PAYLOAD_BYTES: usize = 66;
    pub const GATEWAY_HANDOFF_QUERY_PAYLOAD_BYTES: usize = 18;
    pub const GATEWAY_HANDOFF_STATUS_PAYLOAD_BYTES: usize = 94;
    pub const GATEWAY_HANDOFF_TARGET_VALID_MS: usize = 6000;
    pub const GATEWAY_HANDOFF_RECOVERY_MS: usize = 6000;
    pub const GATEWAY_HANDOFF_RESERVATION_MS: usize = 20000;
    pub const INSTALLATION_ID_DOMAIN: &[u8] = b"keyferry/installation-id/v2";
    pub const LINK_SALT_DOMAIN: &[u8] = b"keyferry/link-salt/v2";
    pub const DEVICE_LINK_DOMAIN: &[u8] = b"keyferry/device-link/v2";
    pub const ROUTE_PROOF_KEY_DOMAIN: &[u8] = b"keyferry/route-proof-key/v2";
    pub const ROUTE_PROOF_DOMAIN: &[u8] = b"keyferry/route-proof/v2";
    pub const POLICY_HASH_DOMAIN: &[u8] = b"keyferry/policy/v2";
    pub const POLICY_AUTH_KEY_DOMAIN: &[u8] = b"keyferry/policy-auth-key/v2";
    pub const POLICY_AUTH_DOMAIN: &[u8] = b"keyferry/policy-auth/v2";
    pub const MAINTENANCE_AUTHENTICATION_DOMAIN: &[u8] = b"keyferry/maintenance/v2";
    pub const DEVICE_GATEWAY_DNS_PREFIX: &[u8] = b"d-";
    pub const DEVICE_GATEWAY_DNS_SUFFIX: &[u8] = b".gateway.keyferry.invalid";
    pub const INSTALLATION_GATEWAY_DNS_PREFIX: &[u8] = b"i-";
    pub const INSTALLATION_GATEWAY_DNS_SUFFIX: &[u8] = b".desktop.keyferry.invalid";
}

pub mod provisioning {
    pub const VERSION: u8 = 1;
    pub const REPORT_SIZE: usize = 64;
    pub const CHALLENGE_SIZE: usize = 32;
    pub const TRANSACTION_ID_SIZE: usize = 16;
    pub const AUTHENTICATION_TAG_SIZE: usize = 32;
    pub const DATA_BYTES_PER_REPORT: usize = 44;
    pub const IDLE_TIMEOUT_MS: u64 = 30000;
    pub const AUTHENTICATION_DOMAIN: &[u8] = b"keyferry-provision-v1";
    pub const REQUEST_OPERATION_OFFSET: usize = 0;
    pub const RESPONSE_OPERATION_OFFSET: usize = 0;
    pub const RESPONSE_STATUS_OFFSET: usize = 1;
    pub const CHALLENGE_VERSION_OFFSET: usize = 2;
    pub const CHALLENGE_PAYLOAD_LENGTH_OFFSET: usize = 3;
    pub const CHALLENGE_DEVICE_ID_OFFSET: usize = 5;
    pub const CHALLENGE_NONCE_OFFSET: usize = 21;
    pub const CHALLENGE_GENERATION_OFFSET: usize = 53;
    pub const BEGIN_VERSION_OFFSET: usize = 1;
    pub const BEGIN_PAYLOAD_LENGTH_OFFSET: usize = 2;
    pub const BEGIN_TRANSACTION_ID_OFFSET: usize = 4;
    pub const DATA_TRANSACTION_ID_OFFSET: usize = 1;
    pub const DATA_OFFSET_OFFSET: usize = 17;
    pub const DATA_LENGTH_OFFSET: usize = 19;
    pub const DATA_BYTES_OFFSET: usize = 20;
    pub const COMMIT_TRANSACTION_ID_OFFSET: usize = 1;
    pub const COMMIT_TAG_OFFSET: usize = 17;
    pub const COMMIT_SLOT_OFFSET: usize = 2;
    pub const COMMIT_GENERATION_OFFSET: usize = 3;
    pub const POLICY_STATUS_STATE_OFFSET: usize = 2;
    pub const POLICY_STATUS_EPOCH_OFFSET: usize = 3;
    pub const POLICY_STATUS_SEQUENCE_OFFSET: usize = 11;
    pub const POLICY_STATUS_HASH_OFFSET: usize = 19;
}

pub mod local_management {
    pub const VERSION: u8 = 1;
    pub const STATUS_SCHEMA: u8 = 1;
    pub const REPORT_SIZE: usize = 64;
    pub const SESSION_ID_SIZE: usize = 8;
    pub const DEVICE_NONCE_SIZE: usize = 32;
    pub const HOST_NONCE_SIZE: usize = 16;
    pub const AUTHENTICATION_TAG_SIZE: usize = 32;
    pub const ENVELOPE_TAG_SIZE: usize = 16;
    pub const OPERATION_ID_SIZE: usize = 16;
    pub const REQUEST_PAYLOAD_SIZE: usize = 18;
    pub const RESPONSE_PAYLOAD_SIZE: usize = 16;
    pub const IDLE_TIMEOUT_MS: u64 = 60000;
    pub const HARD_TIMEOUT_MS: u64 = 300000;
    pub const ENROLLMENT_TIMEOUT_MS: u64 = 120000;
    pub const ADMIN_KEY_DOMAIN: &[u8] = b"keyferry/local-admin-key/v1";
    pub const AUTHENTICATION_DOMAIN: &[u8] = b"keyferry/local-auth/v1";
    pub const SESSION_KEY_DOMAIN: &[u8] = b"keyferry/local-session/v1";
    pub const DEVICE_PROOF_DOMAIN: &[u8] = b"keyferry/local-device-proof/v1";
    pub const REQUEST_DOMAIN: &[u8] = b"keyferry/local-request/v1";
    pub const RESPONSE_DOMAIN: &[u8] = b"keyferry/local-response/v1";
}

pub mod message {
    pub const HELLO: u8 = 0x01;
    pub const GET_STATUS: u8 = 0x02;
    pub const STATUS: u8 = 0x03;
    pub const LEGACY_EXECUTE_REPORTS_RESERVED: u8 = 0x10;
    pub const CANCEL: u8 = 0x11;
    pub const LEGACY_RELEASE_ALL_RESERVED: u8 = 0x12;
    pub const SET_OPERATIONAL_MODE: u8 = 0x13;
    pub const GET_OUTPUT_MODE: u8 = 0x14;
    pub const OUTPUT_MODE_STATUS: u8 = 0x15;
    pub const SET_OUTPUT_MODE: u8 = 0x16;
    pub const RESET_BLE_HID_BOND: u8 = 0x17;
    pub const BLE_HID_BOND_STATUS: u8 = 0x18;
    pub const GET_DISPLAY_ORIENTATION: u8 = 0x19;
    pub const DISPLAY_ORIENTATION_STATUS: u8 = 0x1A;
    pub const SET_DISPLAY_ORIENTATION: u8 = 0x1B;
    pub const GET_SCREEN_POWER: u8 = 0x1C;
    pub const SCREEN_POWER_STATUS: u8 = 0x1D;
    pub const SET_SCREEN_POWER: u8 = 0x1E;
    pub const ACK: u8 = 0x20;
    pub const ERROR: u8 = 0x21;
    pub const LEGACY_USB_STATUS_RESERVED: u8 = 0x22;
    pub const AUTH_CHALLENGE: u8 = 0x40;
    pub const AUTH_RESPONSE: u8 = 0x41;
    pub const SESSION_READY: u8 = 0x42;
    pub const COMMAND: u8 = 0x50;
    pub const COMMAND_RESULT: u8 = 0x51;
    pub const ARM: u8 = 0x52;
    pub const DISARM: u8 = 0x53;
    pub const LEASE_RENEW: u8 = 0x54;
    pub const CAPABILITIES: u8 = 0x55;
    pub const ROUTE_PROOF_REQUEST: u8 = 0x56;
    pub const ROUTE_PROOF_RESPONSE: u8 = 0x57;
    pub const INPUT_COMMAND_RESULT_V1: u8 = 0x58;
    pub const GATEWAY_HANDOFF: u8 = 0x59;
    pub const GATEWAY_HANDOFF_STATUS: u8 = 0x5A;
    pub const FILE_REQUEST: u8 = 0x60;
    pub const FILE_STATUS: u8 = 0x61;
    pub const FILE_SET_REQUEST: u8 = 0x62;
    pub const FILE_SET_STATUS: u8 = 0x63;
}

pub mod command_kind {
    pub const EXECUTE_REPORT_CHUNK: u8 = 0x01;
    pub const CANCEL: u8 = 0x02;
    pub const RELEASE_ALL: u8 = 0x03;
    pub const EXECUTE_INPUT_CHUNK_V1: u8 = 0x04;
    pub const CANCEL_INPUT_SEQUENCE_V1: u8 = 0x05;
    pub const RELEASE_INPUT_ALL_V1: u8 = 0x06;
}

pub mod action {
    pub const KEY_REPORT: u8 = 0x01;
    pub const WAIT_MS: u8 = 0x02;
    pub const RELEASE_ALL_ACTION: u8 = 0x03;
    pub const TAP_KEY: u8 = 0x04;
    pub const MOUSE_MOVE_RELATIVE: u8 = 0x05;
    pub const MOUSE_CLICK: u8 = 0x06;
    pub const NEUTRAL_ALL: u8 = 0x07;
}

pub mod provisioning_operation {
    pub const CHALLENGE: u8 = 0x01;
    pub const BEGIN: u8 = 0x02;
    pub const DATA: u8 = 0x03;
    pub const COMMIT: u8 = 0x04;
    pub const ABORT: u8 = 0x05;
    pub const POLICY_STATUS: u8 = 0x06;
}

pub mod provisioning_policy_state {
    pub const LEGACY: u8 = 0x00;
    pub const ABSENT: u8 = 0x01;
    pub const MALFORMED: u8 = 0x02;
    pub const MIGRATION_PENDING: u8 = 0x03;
    pub const ACTIVE: u8 = 0x04;
    pub const STORAGE_ERROR: u8 = 0x05;
}

pub mod provisioning_status {
    pub const OK: u8 = 0x00;
    pub const BAD_REPORT: u8 = 0x01;
    pub const BAD_STATE: u8 = 0x02;
    pub const BAD_TRANSACTION: u8 = 0x03;
    pub const BAD_OFFSET: u8 = 0x04;
    pub const AUTHENTICATION_FAILED: u8 = 0x05;
    pub const INVALID_CONFIG: u8 = 0x06;
    pub const IDENTITY_MISMATCH: u8 = 0x07;
    pub const COMMIT_FAILED: u8 = 0x08;
    pub const RANDOM_FAILED: u8 = 0x09;
}

pub mod local_management_operation {
    pub const CHALLENGE: u8 = 0x10;
    pub const AUTHENTICATE: u8 = 0x11;
    pub const GET_STATUS: u8 = 0x12;
    pub const OPEN_MAINTENANCE: u8 = 0x13;
    pub const CLOSE_MAINTENANCE: u8 = 0x14;
    pub const RESTART_NETWORK: u8 = 0x15;
    pub const CLEAR_BLE_BOND_AND_ENROLL: u8 = 0x16;
    pub const CANCEL_ENROLLMENT: u8 = 0x17;
    pub const SET_OUTPUT_MODE: u8 = 0x18;
    pub const REBOOT: u8 = 0x19;
    pub const GET_RECEIPT: u8 = 0x1A;
}

pub mod local_management_status {
    pub const OK: u8 = 0x00;
    pub const BAD_REPORT: u8 = 0x01;
    pub const BAD_STATE: u8 = 0x02;
    pub const AUTHENTICATION_FAILED: u8 = 0x03;
    pub const REPLAY: u8 = 0x04;
    pub const BUSY: u8 = 0x05;
    pub const UNSUPPORTED: u8 = 0x06;
    pub const NOT_NEUTRAL: u8 = 0x07;
    pub const OPERATION_UNKNOWN: u8 = 0x08;
    pub const OPERATION_CONFLICT: u8 = 0x09;
    pub const STORAGE_ERROR: u8 = 0x0A;
    pub const IN_PROGRESS: u8 = 0x0B;
    pub const INTERNAL: u8 = 0x7F;
}

pub mod local_management_status_page {
    pub const DEVICE: u8 = 0x01;
    pub const SAFETY: u8 = 0x02;
    pub const NETWORK: u8 = 0x03;
    pub const BLE_HID: u8 = 0x04;
    pub const POLICY: u8 = 0x05;
    pub const LAST_RECEIPT: u8 = 0x06;
    pub const PROBE_RUN: u8 = 0x07;
    pub const PROBE_HEAP: u8 = 0x08;
    pub const PROBE_STACK: u8 = 0x09;
}

pub mod local_management_probe_phase {
    pub const BOOT: u8 = 0x01;
    pub const POST_AUTH: u8 = 0x02;
    pub const FIRST_HELD: u8 = 0x03;
    pub const FIRST_FAILED: u8 = 0x04;
    pub const SECOND_HELD: u8 = 0x05;
    pub const SECOND_FAILED: u8 = 0x06;
    pub const RELEASED: u8 = 0x07;
    pub const INTERRUPTED: u8 = 0x08;
    pub const FLOOR_DROP: u8 = 0x09;
    pub const MONITOR_FAILED: u8 = 0x0A;
    pub const HOLDING: u8 = 0x0B;
    pub const DRIFT: u8 = 0x0C;
    pub const WAITING: u8 = 0x0D;
}

pub mod local_management_probe_outcome {
    pub const NOT_ATTEMPTED: u8 = 0x00;
    pub const SUCCESS: u8 = 0x01;
    pub const GUARD_FAILED: u8 = 0x02;
    pub const CONTIGUOUS_FAILED: u8 = 0x03;
    pub const MALLOC_FAILED: u8 = 0x04;
    pub const POST_GUARD_FAILED: u8 = 0x05;
}

pub mod local_management_bond_state {
    pub const NONE: u8 = 0x00;
    pub const SINGLE: u8 = 0x01;
    pub const MULTIPLE_INVALID: u8 = 0x02;
    pub const STORE_ERROR: u8 = 0x03;
}

pub mod local_management_receipt_state {
    pub const NONE: u8 = 0x00;
    pub const IN_PROGRESS: u8 = 0x01;
    pub const COMMITTED: u8 = 0x02;
    pub const FAILED: u8 = 0x03;
    pub const UNKNOWN: u8 = 0x04;
}

pub mod capability {
    pub const KEYBOARD: u32 = 0x00000001;
    pub const VENDOR_HID_CONFIG: u32 = 0x00000002;
    pub const STATION_MODE: u32 = 0x00000004;
    pub const DIRECT_MODE: u32 = 0x00000008;
    pub const MULTI_WIFI: u32 = 0x00000010;
    pub const BLUETOOTH_GATT: u32 = 0x00000020;
    pub const FIRMWARE_IDENTITY_V1: u32 = 0x00000040;
    pub const MOUSE_RELATIVE_V1: u32 = 0x00010000;
    pub const CONSUMER_KEYS_RESERVED: u32 = 0x00020000;
    pub const REMOTE_WAKE_RESERVED: u32 = 0x00040000;
    pub const BLE_HID_OUTPUT_V1: u32 = 0x00080000;
    pub const BLE_HID_BOND_RESET_V1: u32 = 0x00100000;
    pub const TARGETED_GATEWAY_TRANSFER_V1: u32 = 0x00200000;
    pub const DISPLAY_ORIENTATION_V1: u32 = 0x00400000;
    pub const LOCAL_MANAGEMENT_V1: u32 = 0x00800000;
    pub const USB_FILE_HANDOFF_V1: u32 = 0x01000000;
    pub const SCREEN_POWER_V1: u32 = 0x02000000;
    pub const USB_FILE_SET_V2: u32 = 0x04000000;
}

pub mod output_mode {
    pub const USB_HID: u8 = 0x01;
    pub const BLE_HID: u8 = 0x02;
}

pub mod display_orientation {
    pub const NORMAL: u8 = 0x01;
    pub const ROTATED_180: u8 = 0x02;
}

pub mod screen_power {
    pub const OFF: u8 = 0x01;
    pub const ON: u8 = 0x02;
}

pub mod operational_mode {
    pub const KEYBOARD: u8 = 0x01;
    pub const MAINTENANCE: u8 = 0x02;
    pub const LOCKED: u8 = 0x03;
    pub const FAULT: u8 = 0x04;
}

pub mod arm_policy {
    pub const COMMAND_SCOPED: u8 = 0x01;
    pub const TEMPORARY: u8 = 0x02;
    pub const ALWAYS_READY: u8 = 0x03;
}

pub mod result_code {
    pub const QUEUED: u8 = 0x01;
    pub const ACCEPTED: u8 = 0x02;
    pub const STARTED: u8 = 0x03;
    pub const EMITTED: u8 = 0x04;
    pub const ABORTED: u8 = 0x05;
    pub const REJECTED: u8 = 0x06;
    pub const UNKNOWN: u8 = 0x07;
}

pub mod error_code {
    pub const MALFORMED: u16 = 0x0001;
    pub const UNSUPPORTED_VERSION: u16 = 0x0002;
    pub const UNKNOWN_CRITICAL_FIELD: u16 = 0x0003;
    pub const NOT_AUTHENTICATED: u16 = 0x0004;
    pub const NOT_ARMED: u16 = 0x0005;
    pub const EXPIRED: u16 = 0x0006;
    pub const DUPLICATE: u16 = 0x0007;
    pub const BUSY: u16 = 0x0008;
    pub const INVALID_MODE: u16 = 0x0009;
    pub const USB_UNAVAILABLE: u16 = 0x000A;
    pub const LEGACY_UART_FAULT_RESERVED: u16 = 0x000B;
    pub const CAPABILITY_REQUIRED: u16 = 0x000C;
    pub const LIMIT_EXCEEDED: u16 = 0x000D;
    pub const NEUTRAL_UNCONFIRMED: u16 = 0x000E;
    pub const REPLAY_WINDOW_FULL: u16 = 0x000F;
    pub const CANCELLED: u16 = 0x0010;
    pub const WATCHDOG: u16 = 0x0011;
    pub const INTERNAL: u16 = 0x00FF;
}

pub mod gateway_handoff_operation {
    pub const START: u8 = 0x01;
    pub const ACCEPT: u8 = 0x02;
    pub const QUERY: u8 = 0x03;
}

pub mod gateway_handoff_status {
    pub const OK: u16 = 0x0000;
    pub const BUSY: u16 = 0x0001;
    pub const STALE_PROOF: u16 = 0x0002;
    pub const NOT_READY: u16 = 0x0003;
    pub const UNSUPPORTED: u16 = 0x0004;
    pub const RELEASE_FAILED: u16 = 0x0005;
    pub const UNKNOWN_TRANSACTION: u16 = 0x0006;
    pub const INVALID_TRANSITION: u16 = 0x0007;
}

pub mod gateway_handoff_phase {
    pub const UNKNOWN: u8 = 0x00;
    pub const RELEASING: u8 = 0x01;
    pub const TARGETING: u8 = 0x02;
    pub const TARGET_PROVISIONAL: u8 = 0x03;
    pub const RESTORING: u8 = 0x04;
    pub const TRANSFERRED: u8 = 0x05;
    pub const RESTORED: u8 = 0x06;
    pub const NOT_STARTED: u8 = 0x07;
    pub const RECOVERY_UNAVAILABLE: u8 = 0x08;
}

pub mod gateway_handoff_reason {
    pub const NONE: u8 = 0x00;
    pub const TARGET_ABSENT: u8 = 0x01;
    pub const TRANSPORT_FAILED: u8 = 0x02;
    pub const IDENTITY_FAILED: u8 = 0x03;
    pub const AUTHORIZATION_FAILED: u8 = 0x04;
    pub const ACCEPTANCE_TIMEOUT: u8 = 0x05;
    pub const RELEASE_FAILED: u8 = 0x06;
    pub const PREVIOUS_GATEWAY_UNAVAILABLE: u8 = 0x07;
}
