#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

// @generated by scripts/gen_protocol.py from protocol/messages.yaml.
// Do not edit by hand.
namespace keyferry::protocol {

constexpr std::uint16_t kMagic = 0x4248;
constexpr std::uint8_t kMajor = 1;
constexpr std::uint8_t kMinor = 0;
constexpr std::size_t kHeaderLength = 12;
constexpr std::size_t kCrcLength = 2;
constexpr std::size_t kMaxDecodedFrame = 256;
constexpr std::size_t kMaxPayload = kMaxDecodedFrame - kHeaderLength - kCrcLength;
constexpr std::array<std::uint8_t, 4> kDiscoveryMagic{'K', 'F', 'H', 'B'};
constexpr std::uint8_t kDiscoveryVersion = 1;
constexpr std::size_t kDiscoveryBeaconSize = 22;
constexpr std::uint16_t kDiscoveryPort = 43917;
constexpr std::uint8_t kBleTransportVersion = 1;
constexpr std::array<std::uint8_t, 16> kBleServiceUuid{0xA2, 0xE3, 0xF2, 0xA8, 0xA4, 0xFF, 0x4E, 0xD8, 0x9B, 0x68, 0xDD, 0xE0, 0xE3, 0xAD, 0x76, 0x91};
constexpr std::array<std::uint8_t, 16> kBleGatewayToDeviceUuid{0x74, 0xBE, 0xFF, 0x36, 0x34, 0x49, 0x44, 0xDF, 0x8D, 0xAF, 0x0D, 0xA9, 0xC1, 0x36, 0xF4, 0xAB};
constexpr std::array<std::uint8_t, 16> kBleDeviceToGatewayUuid{0xC9, 0x12, 0xCB, 0xBF, 0xA2, 0xF9, 0x41, 0x8F, 0x98, 0x5C, 0xCC, 0x62, 0x79, 0x38, 0x9C, 0x54};
constexpr std::size_t kBleMinimumAttMtu = 23;
constexpr std::size_t kBlePreferredAttMtu = 247;
constexpr std::size_t kBleMaximumFragmentBytes = 244;
constexpr std::size_t kBleReceiveRingBytes = 1024;
constexpr std::size_t kBleTransmitStagingBytes = 244;
constexpr std::size_t kBleConnectionMetadataMaxBytes = 256;
constexpr std::size_t kBleCccdSetupTimeoutMs = 20000;
constexpr std::size_t kBleAuthenticationTimeoutMs = 20000;
constexpr std::size_t kBleProgressTimeoutMs = 5000;
constexpr std::size_t kBleOperationTimeoutMs = 8000;
constexpr std::size_t kBleHostCandidateTimeoutMs = 40000;
constexpr std::size_t kBleAdvertisingDelayMs = 5000;
constexpr std::size_t kBleWifiPreferenceMs = 15000;
constexpr std::size_t kBleWifiRetryIntervalMs = 30000;
constexpr std::size_t kBleFailedCandidatesBeforeWifiRetry = 3;
constexpr std::uint8_t kRoamingVersion = 2;
constexpr std::uint16_t kRoamingDeviceTlsPort = 7443;
constexpr std::size_t kRoamingInstallationIdBytes = 16;
constexpr std::size_t kRoamingOwnerIdBytes = 16;
constexpr std::size_t kRoamingDeviceIdBytes = 16;
constexpr std::size_t kRoamingRecoverySecretBytes = 32;
constexpr std::size_t kRoamingDeviceLinkSecretBytes = 32;
constexpr std::size_t kRoamingP256SpkiBytes = 91;
constexpr std::size_t kRoamingRouteProofSecretBytes = 32;
constexpr std::size_t kRoamingRouteProofTagBytes = 32;
constexpr std::size_t kRoamingRouteProofBodyBytes = 201;
constexpr std::size_t kRoamingRouteProofFieldsBytes = 178;
constexpr std::size_t kRoamingRouteProofResponseBytes = 210;
constexpr std::size_t kRoamingPolicyAuthTagBytes = 32;
constexpr std::size_t kRoamingRevocationEntryBytes = 16;
constexpr std::size_t kRoamingRoamingConfigFixedHeaderBytes = 192;
constexpr std::size_t kRoamingRoamingConfigPayloadBytes = 3064;
constexpr std::size_t kRoamingPolicyHashInputBytes = 3018;
constexpr std::size_t kRoamingPolicyAuthInputBytes = 55;
constexpr std::size_t kRoamingMaximumRevokedInstallations = 64;
constexpr std::size_t kRoamingRouteProofTtlMs = 5000;
constexpr std::size_t kRoamingGatewayHandoffStartPayloadBytes = 96;
constexpr std::size_t kRoamingGatewayHandoffAcceptPayloadBytes = 66;
constexpr std::size_t kRoamingGatewayHandoffQueryPayloadBytes = 18;
constexpr std::size_t kRoamingGatewayHandoffStatusPayloadBytes = 94;
constexpr std::size_t kRoamingGatewayHandoffTargetValidMs = 6000;
constexpr std::size_t kRoamingGatewayHandoffRecoveryMs = 6000;
constexpr std::size_t kRoamingGatewayHandoffReservationMs = 20000;
constexpr std::array<std::uint8_t, 27> kRoamingInstallationIdDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'i', 'n', 's', 't', 'a', 'l', 'l', 'a', 't', 'i', 'o', 'n', '-', 'i', 'd', '/', 'v', '2'};
constexpr std::array<std::uint8_t, 21> kRoamingLinkSaltDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'l', 'i', 'n', 'k', '-', 's', 'a', 'l', 't', '/', 'v', '2'};
constexpr std::array<std::uint8_t, 23> kRoamingDeviceLinkDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'd', 'e', 'v', 'i', 'c', 'e', '-', 'l', 'i', 'n', 'k', '/', 'v', '2'};
constexpr std::array<std::uint8_t, 27> kRoamingRouteProofKeyDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'r', 'o', 'u', 't', 'e', '-', 'p', 'r', 'o', 'o', 'f', '-', 'k', 'e', 'y', '/', 'v', '2'};
constexpr std::array<std::uint8_t, 23> kRoamingRouteProofDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'r', 'o', 'u', 't', 'e', '-', 'p', 'r', 'o', 'o', 'f', '/', 'v', '2'};
constexpr std::array<std::uint8_t, 18> kRoamingPolicyHashDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'p', 'o', 'l', 'i', 'c', 'y', '/', 'v', '2'};
constexpr std::array<std::uint8_t, 27> kRoamingPolicyAuthKeyDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'p', 'o', 'l', 'i', 'c', 'y', '-', 'a', 'u', 't', 'h', '-', 'k', 'e', 'y', '/', 'v', '2'};
constexpr std::array<std::uint8_t, 23> kRoamingPolicyAuthDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'p', 'o', 'l', 'i', 'c', 'y', '-', 'a', 'u', 't', 'h', '/', 'v', '2'};
constexpr std::array<std::uint8_t, 23> kRoamingMaintenanceAuthenticationDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'm', 'a', 'i', 'n', 't', 'e', 'n', 'a', 'n', 'c', 'e', '/', 'v', '2'};
constexpr std::array<std::uint8_t, 2> kRoamingDeviceGatewayDnsPrefix{'d', '-'};
constexpr std::array<std::uint8_t, 25> kRoamingDeviceGatewayDnsSuffix{'.', 'g', 'a', 't', 'e', 'w', 'a', 'y', '.', 'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '.', 'i', 'n', 'v', 'a', 'l', 'i', 'd'};
constexpr std::array<std::uint8_t, 2> kRoamingInstallationGatewayDnsPrefix{'i', '-'};
constexpr std::array<std::uint8_t, 25> kRoamingInstallationGatewayDnsSuffix{'.', 'd', 'e', 's', 'k', 't', 'o', 'p', '.', 'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '.', 'i', 'n', 'v', 'a', 'l', 'i', 'd'};
constexpr std::uint8_t kProvisioningVersion = 1;
constexpr std::size_t kProvisioningReportSize = 64;
constexpr std::size_t kProvisioningChallengeSize = 32;
constexpr std::size_t kProvisioningTransactionIdSize = 16;
constexpr std::size_t kProvisioningAuthenticationTagSize = 32;
constexpr std::size_t kProvisioningDataBytesPerReport = 44;
constexpr std::uint64_t kProvisioningIdleTimeoutMs = 30000;
constexpr std::array<std::uint8_t, 21> kProvisioningAuthenticationDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '-', 'p', 'r', 'o', 'v', 'i', 's', 'i', 'o', 'n', '-', 'v', '1'};

constexpr std::size_t kConfigMaxWifiProfiles = 8;
constexpr std::size_t kConfigMaxPairedHosts = 8;
constexpr std::size_t kConfigMaxSsidBytes = 32;
constexpr std::size_t kConfigMaxWifiCredentialBytes = 63;
constexpr std::size_t kConfigMaxServerNameBytes = 253;
constexpr std::size_t kConfigMaxCaCertificateBytes = 1024;
constexpr std::size_t kConfigFixedHeaderBytes = 52;
constexpr std::size_t kConfigWifiRecordBytes = 103;
constexpr std::size_t kConfigHostRecordBytes = 1369;
constexpr std::size_t kConfigPayloadBytes = 11828;
constexpr std::size_t kFileHandoffMaxFileBytes = 262144;
constexpr std::size_t kFileHandoffMaxChunkBytes = 200;
constexpr std::size_t kFileHandoffStatusBytes = 10;
constexpr std::size_t kFileHandoffMaxFiles = 16;
constexpr std::size_t kFileHandoffMaxNameBytes = 64;
constexpr std::size_t kFileHandoffFileSetStatusBytes = 11;
constexpr std::size_t kFileHandoffMaxBundleBytes = 1 + kFileHandoffMaxFiles * (1 + kFileHandoffMaxNameBytes + 4) + kFileHandoffMaxFileBytes;
constexpr std::size_t kProvisioningRequestOperationOffset = 0;
constexpr std::size_t kProvisioningResponseOperationOffset = 0;
constexpr std::size_t kProvisioningResponseStatusOffset = 1;
constexpr std::size_t kProvisioningChallengeVersionOffset = 2;
constexpr std::size_t kProvisioningChallengePayloadLengthOffset = 3;
constexpr std::size_t kProvisioningChallengeDeviceIdOffset = 5;
constexpr std::size_t kProvisioningChallengeNonceOffset = 21;
constexpr std::size_t kProvisioningChallengeGenerationOffset = 53;
constexpr std::size_t kProvisioningBeginVersionOffset = 1;
constexpr std::size_t kProvisioningBeginPayloadLengthOffset = 2;
constexpr std::size_t kProvisioningBeginTransactionIdOffset = 4;
constexpr std::size_t kProvisioningDataTransactionIdOffset = 1;
constexpr std::size_t kProvisioningDataOffsetOffset = 17;
constexpr std::size_t kProvisioningDataLengthOffset = 19;
constexpr std::size_t kProvisioningDataBytesOffset = 20;
constexpr std::size_t kProvisioningCommitTransactionIdOffset = 1;
constexpr std::size_t kProvisioningCommitTagOffset = 17;
constexpr std::size_t kProvisioningCommitSlotOffset = 2;
constexpr std::size_t kProvisioningCommitGenerationOffset = 3;
constexpr std::size_t kProvisioningPolicyStatusStateOffset = 2;
constexpr std::size_t kProvisioningPolicyStatusEpochOffset = 3;
constexpr std::size_t kProvisioningPolicyStatusSequenceOffset = 11;
constexpr std::size_t kProvisioningPolicyStatusHashOffset = 19;

constexpr std::uint8_t kLocalManagementVersion = 1;
constexpr std::uint8_t kLocalManagementStatusSchema = 1;
constexpr std::size_t kLocalManagementReportSize = 64;
constexpr std::size_t kLocalManagementSessionIdSize = 8;
constexpr std::size_t kLocalManagementDeviceNonceSize = 32;
constexpr std::size_t kLocalManagementHostNonceSize = 16;
constexpr std::size_t kLocalManagementAuthenticationTagSize = 32;
constexpr std::size_t kLocalManagementEnvelopeTagSize = 16;
constexpr std::size_t kLocalManagementOperationIdSize = 16;
constexpr std::size_t kLocalManagementRequestPayloadSize = 18;
constexpr std::size_t kLocalManagementResponsePayloadSize = 16;
constexpr std::size_t kLocalManagementIdleTimeoutMs = 60000;
constexpr std::size_t kLocalManagementHardTimeoutMs = 300000;
constexpr std::size_t kLocalManagementEnrollmentTimeoutMs = 120000;
constexpr std::array<std::uint8_t, 27> kLocalManagementAdminKeyDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'l', 'o', 'c', 'a', 'l', '-', 'a', 'd', 'm', 'i', 'n', '-', 'k', 'e', 'y', '/', 'v', '1'};
constexpr std::array<std::uint8_t, 22> kLocalManagementAuthenticationDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'l', 'o', 'c', 'a', 'l', '-', 'a', 'u', 't', 'h', '/', 'v', '1'};
constexpr std::array<std::uint8_t, 25> kLocalManagementSessionKeyDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'l', 'o', 'c', 'a', 'l', '-', 's', 'e', 's', 's', 'i', 'o', 'n', '/', 'v', '1'};
constexpr std::array<std::uint8_t, 30> kLocalManagementDeviceProofDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'l', 'o', 'c', 'a', 'l', '-', 'd', 'e', 'v', 'i', 'c', 'e', '-', 'p', 'r', 'o', 'o', 'f', '/', 'v', '1'};
constexpr std::array<std::uint8_t, 25> kLocalManagementRequestDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'l', 'o', 'c', 'a', 'l', '-', 'r', 'e', 'q', 'u', 'e', 's', 't', '/', 'v', '1'};
constexpr std::array<std::uint8_t, 26> kLocalManagementResponseDomain{'k', 'e', 'y', 'f', 'e', 'r', 'r', 'y', '/', 'l', 'o', 'c', 'a', 'l', '-', 'r', 'e', 's', 'p', 'o', 'n', 's', 'e', '/', 'v', '1'};

enum class MessageType : std::uint8_t {
  kHello = 0x01,
  kGetStatus = 0x02,
  kStatus = 0x03,
  kLegacyExecuteReportsReserved = 0x10,
  kCancel = 0x11,
  kLegacyReleaseAllReserved = 0x12,
  kSetOperationalMode = 0x13,
  kGetOutputMode = 0x14,
  kOutputModeStatus = 0x15,
  kSetOutputMode = 0x16,
  kResetBleHidBond = 0x17,
  kBleHidBondStatus = 0x18,
  kGetDisplayOrientation = 0x19,
  kDisplayOrientationStatus = 0x1A,
  kSetDisplayOrientation = 0x1B,
  kGetScreenPower = 0x1C,
  kScreenPowerStatus = 0x1D,
  kSetScreenPower = 0x1E,
  kAck = 0x20,
  kError = 0x21,
  kLegacyUsbStatusReserved = 0x22,
  kAuthChallenge = 0x40,
  kAuthResponse = 0x41,
  kSessionReady = 0x42,
  kCommand = 0x50,
  kCommandResult = 0x51,
  kArm = 0x52,
  kDisarm = 0x53,
  kLeaseRenew = 0x54,
  kCapabilities = 0x55,
  kRouteProofRequest = 0x56,
  kRouteProofResponse = 0x57,
  kInputCommandResultV1 = 0x58,
  kGatewayHandoff = 0x59,
  kGatewayHandoffStatus = 0x5A,
  kFileRequest = 0x60,
  kFileStatus = 0x61,
  kFileSetRequest = 0x62,
  kFileSetStatus = 0x63,
};

enum class CommandKind : std::uint8_t {
  kExecuteReportChunk = 0x01,
  kCancel = 0x02,
  kReleaseAll = 0x03,
  kExecuteInputChunkV1 = 0x04,
  kCancelInputSequenceV1 = 0x05,
  kReleaseInputAllV1 = 0x06,
};

enum class ReportAction : std::uint8_t {
  kKeyReport = 0x01,
  kWaitMs = 0x02,
  kReleaseAllAction = 0x03,
  kTapKey = 0x04,
  kMouseMoveRelative = 0x05,
  kMouseClick = 0x06,
  kNeutralAll = 0x07,
};

enum class ProvisioningOperation : std::uint8_t {
  kChallenge = 0x01,
  kBegin = 0x02,
  kData = 0x03,
  kCommit = 0x04,
  kAbort = 0x05,
  kPolicyStatus = 0x06,
};

enum class ProvisioningPolicyState : std::uint8_t {
  kLegacy = 0x00,
  kAbsent = 0x01,
  kMalformed = 0x02,
  kMigrationPending = 0x03,
  kActive = 0x04,
  kStorageError = 0x05,
};

enum class ProvisioningStatus : std::uint8_t {
  kOk = 0x00,
  kBadReport = 0x01,
  kBadState = 0x02,
  kBadTransaction = 0x03,
  kBadOffset = 0x04,
  kAuthenticationFailed = 0x05,
  kInvalidConfig = 0x06,
  kIdentityMismatch = 0x07,
  kCommitFailed = 0x08,
  kRandomFailed = 0x09,
};

enum class LocalManagementOperation : std::uint8_t {
  kChallenge = 0x10,
  kAuthenticate = 0x11,
  kGetStatus = 0x12,
  kOpenMaintenance = 0x13,
  kCloseMaintenance = 0x14,
  kRestartNetwork = 0x15,
  kClearBleBondAndEnroll = 0x16,
  kCancelEnrollment = 0x17,
  kSetOutputMode = 0x18,
  kReboot = 0x19,
  kGetReceipt = 0x1A,
};

enum class LocalManagementStatus : std::uint8_t {
  kOk = 0x00,
  kBadReport = 0x01,
  kBadState = 0x02,
  kAuthenticationFailed = 0x03,
  kReplay = 0x04,
  kBusy = 0x05,
  kUnsupported = 0x06,
  kNotNeutral = 0x07,
  kOperationUnknown = 0x08,
  kOperationConflict = 0x09,
  kStorageError = 0x0A,
  kInProgress = 0x0B,
  kInternal = 0x7F,
};

enum class LocalManagementStatusPage : std::uint8_t {
  kDevice = 0x01,
  kSafety = 0x02,
  kNetwork = 0x03,
  kBleHid = 0x04,
  kPolicy = 0x05,
  kLastReceipt = 0x06,
  kProbeRun = 0x07,
  kProbeHeap = 0x08,
  kProbeStack = 0x09,
};

enum class LocalManagementProbePhase : std::uint8_t {
  kBoot = 0x01,
  kPostAuth = 0x02,
  kFirstHeld = 0x03,
  kFirstFailed = 0x04,
  kSecondHeld = 0x05,
  kSecondFailed = 0x06,
  kReleased = 0x07,
  kInterrupted = 0x08,
  kFloorDrop = 0x09,
  kMonitorFailed = 0x0A,
  kHolding = 0x0B,
  kDrift = 0x0C,
  kWaiting = 0x0D,
};

enum class LocalManagementProbeOutcome : std::uint8_t {
  kNotAttempted = 0x00,
  kSuccess = 0x01,
  kGuardFailed = 0x02,
  kContiguousFailed = 0x03,
  kMallocFailed = 0x04,
  kPostGuardFailed = 0x05,
};

enum class LocalManagementBondState : std::uint8_t {
  kNone = 0x00,
  kSingle = 0x01,
  kMultipleInvalid = 0x02,
  kStoreError = 0x03,
};

enum class LocalManagementReceiptState : std::uint8_t {
  kNone = 0x00,
  kInProgress = 0x01,
  kCommitted = 0x02,
  kFailed = 0x03,
  kUnknown = 0x04,
};

enum class Capability : std::uint32_t {
  kKeyboard = 0x00000001,
  kVendorHidConfig = 0x00000002,
  kStationMode = 0x00000004,
  kDirectMode = 0x00000008,
  kMultiWifi = 0x00000010,
  kBluetoothGatt = 0x00000020,
  kFirmwareIdentityV1 = 0x00000040,
  kMouseRelativeV1 = 0x00010000,
  kConsumerKeysReserved = 0x00020000,
  kRemoteWakeReserved = 0x00040000,
  kBleHidOutputV1 = 0x00080000,
  kBleHidBondResetV1 = 0x00100000,
  kTargetedGatewayTransferV1 = 0x00200000,
  kDisplayOrientationV1 = 0x00400000,
  kLocalManagementV1 = 0x00800000,
  kUsbFileHandoffV1 = 0x01000000,
  kScreenPowerV1 = 0x02000000,
  kUsbFileSetV2 = 0x04000000,
};

enum class OutputMode : std::uint8_t {
  kUsbHid = 0x01,
  kBleHid = 0x02,
};

enum class DisplayOrientation : std::uint8_t {
  kNormal = 0x01,
  kRotated180 = 0x02,
};

enum class ScreenPower : std::uint8_t {
  kOff = 0x01,
  kOn = 0x02,
};

enum class OperationalMode : std::uint8_t {
  kKeyboard = 0x01,
  kMaintenance = 0x02,
  kLocked = 0x03,
  kFault = 0x04,
};

enum class ArmPolicy : std::uint8_t {
  kCommandScoped = 0x01,
  kTemporary = 0x02,
  kAlwaysReady = 0x03,
};

enum class ResultCode : std::uint8_t {
  kQueued = 0x01,
  kAccepted = 0x02,
  kStarted = 0x03,
  kEmitted = 0x04,
  kAborted = 0x05,
  kRejected = 0x06,
  kUnknown = 0x07,
};

enum class ErrorCode : std::uint16_t {
  kMalformed = 0x0001,
  kUnsupportedVersion = 0x0002,
  kUnknownCriticalField = 0x0003,
  kNotAuthenticated = 0x0004,
  kNotArmed = 0x0005,
  kExpired = 0x0006,
  kDuplicate = 0x0007,
  kBusy = 0x0008,
  kInvalidMode = 0x0009,
  kUsbUnavailable = 0x000A,
  kLegacyUartFaultReserved = 0x000B,
  kCapabilityRequired = 0x000C,
  kLimitExceeded = 0x000D,
  kNeutralUnconfirmed = 0x000E,
  kReplayWindowFull = 0x000F,
  kCancelled = 0x0010,
  kWatchdog = 0x0011,
  kInternal = 0x00FF,
};

enum class GatewayHandoffOperation : std::uint8_t {
  kStart = 0x01,
  kAccept = 0x02,
  kQuery = 0x03,
};

enum class GatewayHandoffStatus : std::uint16_t {
  kOk = 0x0000,
  kBusy = 0x0001,
  kStaleProof = 0x0002,
  kNotReady = 0x0003,
  kUnsupported = 0x0004,
  kReleaseFailed = 0x0005,
  kUnknownTransaction = 0x0006,
  kInvalidTransition = 0x0007,
};

enum class GatewayHandoffPhase : std::uint8_t {
  kUnknown = 0x00,
  kReleasing = 0x01,
  kTargeting = 0x02,
  kTargetProvisional = 0x03,
  kRestoring = 0x04,
  kTransferred = 0x05,
  kRestored = 0x06,
  kNotStarted = 0x07,
  kRecoveryUnavailable = 0x08,
};

enum class GatewayHandoffReason : std::uint8_t {
  kNone = 0x00,
  kTargetAbsent = 0x01,
  kTransportFailed = 0x02,
  kIdentityFailed = 0x03,
  kAuthorizationFailed = 0x04,
  kAcceptanceTimeout = 0x05,
  kReleaseFailed = 0x06,
  kPreviousGatewayUnavailable = 0x07,
};

}  // namespace keyferry::protocol
